name: Build with Nuitka
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install orderedset package
        run: pip install orderedset
      - name: Build python script into a stand-alone executable
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          standalone: true # changed this line from standalone-mode to standalone
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-${{ matrix.os }}
          path: main.exe
